apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis
  labels:
    app: iis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iis
  template:
    metadata:
      labels:
        app: iis
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: iis-server
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-2004
        ports:
        - containerPort: 80
        env:
          - name: RKE2_COREDNS_RKE2_COREDNS_SERVICE_HOST
            value: "10.43.0.10"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP
            value: "tcp://10.43.0.10:53"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP_ADDR
            value: "10.43.0.10"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP_PORT
            value: "53"
          - name: RKE2_COREDNS_RKE2_COREDNS_SERVICE_PORT
            value: "53"
          - name: RKE2_COREDNS_RKE2_COREDNS_SERVICE_PORT_TCP_53
            value: "53"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP_PROTO
            value: "tcp"
